apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facebooc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-secret
  rules:
  - host: "facebooc.tibchannels.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: facebooc
            port:
              number: 16000